@Test_HostAddress = http://localhost:5192

### Post Add Capacity Record

POST {{Test_HostAddress}}/api/v1/products/capacity
Content-Type: application/json

{
  "productId": 1,
  "quantity": 100
}

### Get Products

GET {{Test_HostAddress}}/api/v1/products

### Post Add Product Record

POST {{Test_HostAddress}}/api/v1/products
Content-Type: application/json

{
  "name": "Product Name",
  "quantity": 50
}

### Post Receive Product

POST {{Test_HostAddress}}/api/v1/products/receive
Content-Type: application/json

{
  "productId": 1,
  "quantity": 20
}

### Post Dispatch Product

POST {{Test_HostAddress}}/api/v1/products/dispatch
Content-Type: application/json

{
  "productId": 1,
  "quantity": 10
}